### ISSUE TITLE
Error PaletteManipulator during update with Manager

### ISSUE THREAD

**Issue by planepix** [ausi/slug-generator#10]
Hi Ausi,

reported an error in contao manager repo; but guess it depends on your slug bundle:
https://github.com/contao/contao-manager/issues/226

After removing the bundle all runs quite well.
I will try to set an older version of the bundle to be able to use it anyway.

Thank you.
All best
Thomas

**Comment by fritzmg** [comment]
This is an issue of [ausi/contao-slug-backport](https://github.com/ausi/contao-slug-backport), not ausi/slug-generator. See https://github.com/ausi/contao-slug-backport/issues/2

**Comment by ausi** [comment]
Fixed in version 1.0.3
