### ISSUE TITLE
Class 'SlugGenerator' not found

### ISSUE THREAD

**Issue by timblanq** [ausi/slug-generator#14]
I installed the Slug Generator via composer, but it doesn't work. Every time i try to use it, i get an php error: "Uncaught Error: Class 'Ausi\SlugGenerator' not found".

Tried it with including the autoload.php and also by directly including the source files.

What could be the problem, all the other required packages are working as they should.

**Comment by ausi** [comment]
Looks like you used the wrong class name, `Ausi\SlugGenerator\SlugGenerator` is the correct one.

You can use it like so:

```
use Ausi\SlugGenerator\SlugGenerator;
new SlugGenerator(…);
```
