### ISSUE TITLE
Attempted to load class "Normalizer" from the global namespace.

### ISSUE THREAD

**Issue by pegasus1982** [ausi/slug-generator#21]
I installed this package in symfony 4 project.

I followed the steps to generate slug.
But I got this error.
![image](https://user-images.githubusercontent.com/38883905/89524524-4f081a80-d817-11ea-8248-844dcf8ebfa4.png)

How can I solve this issue?

**Comment by ausi** [comment]
The error message indicates that the PHP intl extension is not installed or not activated.

Please check the `intl` section in your phpinfo to see if the extension is active.

**Comment by pegasus1982** [comment]
Of course I activated php intl extension.

**Comment by ausi** [comment]
But the `Normalizer` class is still not available?

Can you please check if the `Locale` class is present in your PHP setup?  
`var_dump(class_exists('Locale'));`

**Comment by pegasus1982** [comment]
Let me check

**Comment by pegasus1982** [comment]
it returns **bool(true)**.

**Comment by pegasus1982** [comment]
![image](https://user-images.githubusercontent.com/38883905/89557080-dd46c580-d844-11ea-9307-6608ea60ae16.png)
![image](https://user-images.githubusercontent.com/38883905/89557148-f485b300-d844-11ea-8304-37461ac4ac9e.png)

**Comment by ausi** [comment]
And `var_dump(class_exists('Normalizer'));` is `false` ?

**Comment by pegasus1982** [comment]
No it is **bool(true)**.

**Comment by pegasus1982** [comment]
The weird thing is that this package works on windows, but my server was installed on ubuntu.
And I want it would work definitely.
But it doesn't work.

**Comment by ausi** [comment]
In the initial comment you posted the error message of a `ClassNotFoundException` which cannot happen if `class_exists('Normalizer')` returns `true`.

Are you sure you executed the `class_exists()` code in the same environment where the slug library shows this error?

**Comment by pegasus1982** [comment]
Let me check

**Comment by pegasus1982** [comment]
Well, it always returns **true**

**Comment by ausi** [comment]
Even if you put the `var_dump(class_exists('Normalizer'));` in the file *vendor/ausi/slug-generator/src/SlugGenerator.php* on line 79: https://github.com/ausi/slug-generator/blob/e4414ac2b934565968d3c9ed4d4d591f134a3051/src/SlugGenerator.php#L79-L80
you get `true` but a `ClassNotFoundException` gets thrown on the next line?

**Comment by ausi** [comment]
@pegasus1982 any updates on this?

**Comment by pegasus1982** [comment]
I uninstalled php and installed all from scratch.
And it worked now.
