### ISSUE TITLE
Support for php >8.1

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [ausi/slug-generator#32]
Hi, i'm using this package with my laravel application, i want to upgrade laravel to version 10 and now it's require to use php 8.1.
Can you add support to this php version?

thanks

**Comment by ausi** [comment]
PHP 8.1 is already supported by this library.
Do you have any issues with it on PHP 8.1?

**Comment by EM-LilianaIturribarria** [comment]
i'm so sorry, you are right. i was using version 1.1.0, and 1.1.1 is the one that has php 8.1 support
