### ISSUE TITLE
Why not compatible with PHP 7.0?

### ISSUE THREAD

**Issue by chrisidakwo** [ausi/slug-generator#6]
So you created this awesome tool just to refuse PHP 7.0? Not fair! Yes I created an issue just to say that!

**Comment by ausi** [comment]
The library uses some features that aren’t available in PHP 7.0.

Active support for PHP 7.0 ends in 17 days, so I thought there is no need to support older versions than 7.1.

I also looked at other libraries. Symfony for example requires PHP 7.1 too.

Are there any good reasons to add support for PHP 7.0? If so, I might add support for it in the next version.

**Comment by chrisidakwo** [comment]
No good reason at all. Well, except that I currently work with PHP 7.0. It's been helpful though. Great work.

**Comment by ausi** [comment]
Please keep in mind that [PHP 7.0 is no longer in active support](http://php.net/supported-versions.php) since two days. Upgrading to 7.1 or 7.2 is highly recommended.

**Comment by chrisidakwo** [comment]
Yeah, I know that.
