### ISSUE TITLE
Unsupported declare 'strict_types' + Fatal error 

### ISSUE THREAD

**Issue by ezetojo** [ausi/slug-generator#7]
I'm getting this while using the generator. Any idea? Thank you!

Warning: Unsupported declare 'strict_types' in SlugGenerator.php on line 12
Fatal error: Default value for parameters with a class type hint can only be NULL in SlugGenerator.php on line 36

**Comment by ausi** [comment]
Which PHP version are you using?

**Comment by ezetojo** [comment]
@ausi PHP 5.6.29

**Comment by ausi** [comment]
For this library you need at least PHP 7.1.0. Composer should have checked that automatically at installation.

**Comment by ezetojo** [comment]
@ausi oh, ok, my bad. i installed it manually. thanks btw
