### ISSUE TITLE
Contao: Alias-Generierung bei News und Seitenstruktur unterschiedlich

### ISSUE THREAD

**Issue by derastronaut** [ausi/slug-generator#8]
Hallo,

ich habe den slug-generator in Contao 4.4.13 installiert und gerade festgestellt, dass bei der Einstellung "ASCII-Zahlen und Kleinbuchstaben" im News-Modul aus runden Klammern 40 bzw. 41 (der ASCII-Tabelle nach) im Alias werden. Erstelle ich eine neue Seite unter Seitenstruktur oder lasse ein Alias neu generieren, werden Klammern, wie man es aus Contao 3.5 kennt, in Bindestriche/Minus umgewandelt.

Da andere Satzzeichen im News-Modul nach bekanntem Schema ersetzt werden gehe ich von einem Bug im aus.

Gruß
Sebastian

**Comment by ausi** [comment]
Duplicate of contao/core-bundle#1334
