### ISSUE TITLE
Add requirement for ICU 4.6

### ISSUE THREAD

**Issue by ausi** [ausi/slug-generator#9]
We should add a requirement for `"lib-icu": ">=4.6"` because this is the version where the transform rule `Latin-ASCII` was added (CLDR 1.9).

See contao/core-bundle#1352

**Comment by fritzmg** [comment]
Though this will still enable you to install `1.0.0`.

**Comment by ausi** [comment]
Yes, but I’m afraid there is nothing we can do about that.

**Comment by fritzmg** [comment]
True, but the next `contao/core-bundle` and `ausi/contao-slug-backport` version should probably change the requirement to `^1.0.1`.

* https://github.com/contao/core-bundle/pull/1375
* https://github.com/ausi/contao-slug-backport/pull/3
